### ISSUE TITLE
[bug] I have 2163 ion lost in a transaction address I cannot get access to

### ISSUE THREAD

**Issue by raid12345678** [ioncoincore/ion-v4#166]
I transferred Ion from ionomy.com to my ION QT. The address I used was the pre-populated address in my wallet which is as follows: ipDuc3ZW7ZHiXy3seLaHjjnKLGqrvg4epr
In screenshot labeled: ION QT Receive address 

after waiting 4 hours my ION coin did not send to my wallet.

**To Reproduce**
1. I previously had installed ION QT back in February. I did a reinstalled of the ION qt by finding the current releases and installing  "ion-3.1.01-win64-setup-unsigned"
Once installed I synced the full ION blockchain after 8 hours I decided to turn on Encryption on my wallet and set a password Screenshot labeled: Encrypt wallet on ION QT

2. With wallet installed and synced and encryption turned on I then restarted my wallet and made sure the encryption had taken affect. I let it sync and looked good I then waited 20 minutes. I now Sent coin from Ionomy.com to my address populated in my QT  ipDuc3ZW7ZHiXy3seLaHjjnKLGqrvg4epr.

Here is the Ionomy.com screenshot confirming withdraw labeled: Ionomy com withdrawal 
The link on View transaction sends me to the following link: https://chainz.cryptoid.info/ion/tx.dws?5a7aba31edbe5dfd83bfaf5257b6a6a3679826135a500f13211d8ecdf5a8fc66

The screenshot for the link is labeled: Ionomy com list to chainz

 
3. The Ionomy.com site confirms my transaction that was sent from Ionomy.com to the ION QT that was pre populated as shown in sceenshot "ION QT Receive address" is the correct address it was sent to. I waited the 4 hours and was confused as to where my ION coin went. I then ran the following wallet repair function on my current wallet found a Tools -> Wallet Repair -> Recover transactions 1 to see if there was in issue on the QT. You can find the screenshot of what I tried in screenshot labeled "ION QT Recover transactions 1". After running this I still did not see my ION coin.

4. I then ran the QT wallet repair function called Rebuild Index thinking my dat file might be corrupt. The function I ran can be found in screen shot labeled: " ION QT rebuild index"

I then let the wallet resync and left the wallet for 24 hours and my ION had still show in my wallet.

5 I then talked with a member of the ION support team. That member asked me to do the following on the screenshot ION QT Receiving tab please check the box Reuse an existing receiving address. I checked that box and then was asked to click on Receiving Address button.
You can see in the screenshot labled "ION QT Receiving tab checkbox and button"

In the ION QT -> Receiving tab-> Receiving Addresses button page there was not ION Address for receiving payments listed. You can see the result in screenshot labeled "ION QT - Receiving tab - Receiving Addresses Button page"

I was told to generate a receiving address by hitting the button new - see screenshot labeled "ION QT - Receiving tab - Receiving Address page - New button" 

The address that was presented and the "Pre populated in my Receiving Address tab then changed from  ipDuc3ZW7ZHiXy3seLaHjjnKLGqrvg4epr at listed in screenshot "ION QT Receive address" to a different address "imz6qPPgDTZGCwjw2ZGu4coZhaZSyQoPZr" which can been in currently as my default populated Receiving address on my Wallet by viewing screenshot labeled: "ION QT - Receiving tab - Receiving Addresses Button page" in the background. 

6 I proceeded to try the following command which was advised to me from the ION support member to  run my debug console and check the following command "dumpprivkey ipDuc3ZW7ZHiXy3seLaHjjnKLGqrvg4epr" The information got back from the debug console was "Private key for address ipDuc3ZW7ZHiXy3seLaHjjnKLGqrvg4epr is not known (code -4)"
look at screenshot labled "ION QT - Debug console - dumpprivkey"

I am not sure what to do at this point I have copied my backup dat files in the ion qt backup files found here "C:\Users\Home1\AppData\Roaming\ioncoin\backups" and I tried restoring eveyone of those dat files and still nothing has the receiving address priv key or my ION coins.
 

**Expected behavior**
When a Receiving address is listed in a QT pre-populated as a user my assumption is that address is a valid address to receive coin and should be linked to my wallet. I would not understand it I have to hit New address if an address is already posted as being on my wallet.
So When I sent coins I should have received them  to my QT wallet from that address.

**Desktop (please complete the following information):**
 - Windows 10 Pro 64bit
version 1803
 - QT Ion Core version v3.1.01 (64-bit)

![Encrypt wallet on ION QT](https://user-images.githubusercontent.com/10733970/60997465-80fd3380-a31c-11e9-9664-0558e20fe52d.png)
![ION QT - Debug console - dumpprivkey](https://user-images.githubusercontent.com/10733970/60997466-80fd3380-a31c-11e9-9cc0-1f2b2db627e0.jpg)
![ION QT - Receiving tab - Receiving Address page - New button](https://user-images.githubusercontent.com/10733970/60997467-80fd3380-a31c-11e9-9cda-71440a2ff793.png)
![ION QT - Receiving tab - Receiving Addresses Button page](https://user-images.githubusercontent.com/10733970/60997468-80fd3380-a31c-11e9-82e8-d8eb3b069694.png)
![ION QT Rebuild index](https://user-images.githubusercontent.com/10733970/60997469-80fd3380-a31c-11e9-8a3b-b8ee2f3feb79.png)
![ION QT Receive address](https://user-images.githubusercontent.com/10733970/60997470-80fd3380-a31c-11e9-99df-7de785671558.png)
![ION QT Receiving tab checkbox and button](https://user-images.githubusercontent.com/10733970/60997471-80fd3380-a31c-11e9-9ea4-0b5c76dc6d43.png)
![ION QT Recover transactions 1](https://user-images.githubusercontent.com/10733970/60997472-80fd3380-a31c-11e9-8028-930fee9e0b7d.png)
![Ionomy com list to chainz](https://user-images.githubusercontent.com/10733970/60997474-8195ca00-a31c-11e9-8e84-747151a2e8a6.png)
![Ionomy com withdrawal](https://user-images.githubusercontent.com/10733970/60997475-8195ca00-a31c-11e9-8b60-830906c59799.png)

**Comment by krumblez** [comment]
Aside from this reported bug, do you have any old wallet.dat files backed up from the previous installation on your computer, even in an erroneous location on a machine, usb backup or otherwise?

You can search your computer in the file explorer by typing wallet.dat in the search bar and hitting return, then check the folder location to see if perhaps it may be relevant.

**Comment by raid12345678** [comment]
I currently have 56 backup wallet.dats on my computer related to ION wallet. 
There is the standard back
![Screenshot_3](https://user-images.githubusercontent.com/10733970/61000907-10f2ab80-a324-11e9-8172-99f083350ea6.png)
![Screenshot_10](https://user-images.githubusercontent.com/10733970/61000912-13550580-a324-11e9-879b-955588c89555.png)

 wallet dat file in IONcoin

**Comment by krumblez** [comment]
Did you try the 1280kb backup, it is best to backup all files in your current data directory to a secure marked location, copy back the peers.dat file and that 1280kb file and see what happens on wallet start up, turn on coin control and click send when started, you can then see from coin control if the address you sent ION to is there within that wallet.dat file - This method is somewhat quicker than the Debug Console method I feel. (getaaddressgroupings)

**Comment by krumblez** [comment]
![image](https://user-images.githubusercontent.com/11175971/61001298-4a90da00-a357-11e9-9c1b-dddf87bb43a4.png)

**Comment by raid12345678** [comment]
The dat with 1280kb I have added that to my wallet I get this 
![Wallet dat 1280 kb](https://user-images.githubusercontent.com/10733970/61057371-cd974c00-a3ba-11e9-8866-030fc618ece7.png)

**Comment by krumblez** [comment]
Ok, try this one, please.

![image](https://user-images.githubusercontent.com/11175971/61063027-2edd1080-a3f7-11e9-8a49-efc1e23489c2.png)

**Comment by raid12345678** [comment]
When I op[en the wallet this is what I see in Send tab -> Open Coin Control-> Coin Selection
![Screenshot_15](https://user-images.githubusercontent.com/10733970/61064822-1b668100-a3c8-11e9-9fbd-9f736c6211a8.png)

**Comment by FornaxA** [comment]
OK so this could indeed be an issue.
Here you see how I don't have the private key *at the moment* the public key is displayed.
For now: just press 'Request payment'. I'll go and see a) if this happens in newer versions, b) why it happens.

![Screenshot from 2019-07-11 19-25-18](https://user-images.githubusercontent.com/25762277/61071547-ad46ac00-a411-11e9-9192-0280c798df06.png)

**Comment by FornaxA** [comment]
This address is stored (and retrieved) through the Qt settings:
https://github.com/ioncoincore/ion/blob/v3.1.02/src/qt/receivecoinsdialog.cpp#L104

This makes it very well possible that the private key can be found in any of the other wallet.dat files that you have in any other folder. The one you used when this functionality was first introduced..

If you'd be using Linux or OSX, I could give you a pywallet script that would scan your disk for private keys.. In your case, perhaps try to read those other wallet.dat files through the Qt..

**Comment by FornaxA** [comment]
This behavior seems to be changed/fixed in the next update.

**Comment by cevap** [comment]
@raid12345678 does the problem persist with new client and if no, can we close this issue?
